const JAEditorTranslation = {
    "start":"プロジェクトの開始",
    "projects":{
        "new":"新しいプロジェクト",
        "open":"プロジェクトを開く",
        "newChart":"新しいチャート",
        "convertChart":"チャートを変換",
        "newBehavior":"新しいビヘイビア"
    },
    "chartEditor":{
        "testPlay":"テストプレイ",
        "export":"エクスポート",
        "save":"保存",
        "menuTab":{
            "overView":"概要",
            "metadata":"メタデータ",
            "music":"楽曲",
            "chart":"譜面"
        },
        "overView":{
            "title":"概要(読み取り専用)",
            "stats":{
                "title":"統計",
                "musics":"楽曲",
                "charts":"チャート"
            }
        },
        "metadata":{
            "title":"メタデータ",
            "bpm":"BPM",
            "name":"タイトル",
            "composer":"楽曲コンポーザ",
            "license":"ライセンス",
            "time":"時間(秒)",
            "thumbnail":"サムネイル画像",
            "changeimg":"変更"
        },
        "music":{
            "title":"楽曲",
            "default":"デフォルト楽曲",
            "all":"すべての楽曲",
            "add":"追加"
        },
        "chart":{
            "title":"チャート",
            "scale":"拡大率",
            "quantize":"クオンタイズ",
            "positionBase":"配置フォーマット",
            "beatBase":"拍",
            "timeBase":"時間",
            "properties":{
                "overView":"概要",
                "note":"ノート詳細",
                "code":"コード"
            }
        }
    },
    "converter":{
        "input":{
            "convert":"チャートを変換",
            "file":"ファイルを選択",
            "fileName":"ファイル:",
            "selectedFile":"選択されていません。",
            "selectType":"変換方法を選択",
            "direction":"変換モード",
            "type":"ファイルの形式",
            "output":"出力"
        }
    }
}
export default JAEditorTranslation;