// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ja'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * こ​ん​に​ち​は
	 */
	hello: string
	Scenes: {
		Splash: {
			Notice: {
				/**
				 * ゲ​ー​ム​開​始​前​に​お​読​み​く​だ​さ​い
				 */
				title: string
				/**
				 * 点​滅​や​光​の​刺​激​に​よ​り​,​目​の​痛​み​や​痙​攣​な​ど​を​起​こ​す​場​合​が​あ​り​ま​す​。​症​状​の​あ​る​方​は​ご​注​意​く​だ​さ​い​。​
			​長​時​間​の​プ​レ​イ​は​控​え​,​適​度​に​休​憩​を​取​る​よ​う​に​し​て​く​だ​さ​い​。​頭​痛​や​め​ま​い​,​疲​労​感​な​ど​の​体​調​不​良​を​感​じ​た​と​き​は​す​ぐ​に​プ​レ​イ​を​中​止​し​て​く​だ​さ​い​。​症​状​が​改​善​し​な​い​場​合​は​,​医​師​に​相​談​し​て​く​だ​さ​い​。​
			​ゲ​ー​ム​プ​レ​イ​時​に​は​,​必​ず​ル​ー​ル​や​マ​ナ​ー​,​利​用​規​約​を​遵​守​し​,​す​べ​て​の​プ​レ​イ​ヤ​ー​が​快​適​に​遊​べ​る​よ​う​心​が​け​て​く​だ​さ​い​。
				 */
				content: string
			}
		}
		Title: {
			/**
			 * ク​リ​ッ​ク​し​て​開​始
			 */
			start: string
		}
	}
	Global: {
		/**
		 * F​e​a​t​u​r​e​ ​M​e
		 */
		title: string
	}
}

export type TranslationFunctions = {
	/**
	 * こんにちは
	 */
	hello: () => LocalizedString
	Scenes: {
		Splash: {
			Notice: {
				/**
				 * ゲーム開始前にお読みください
				 */
				title: () => LocalizedString
				/**
				 * 点滅や光の刺激により,目の痛みや痙攣などを起こす場合があります。症状のある方はご注意ください。
			長時間のプレイは控え,適度に休憩を取るようにしてください。頭痛やめまい,疲労感などの体調不良を感じたときはすぐにプレイを中止してください。症状が改善しない場合は,医師に相談してください。
			ゲームプレイ時には,必ずルールやマナー,利用規約を遵守し,すべてのプレイヤーが快適に遊べるよう心がけてください。
				 */
				content: () => LocalizedString
			}
		}
		Title: {
			/**
			 * クリックして開始
			 */
			start: () => LocalizedString
		}
	}
	Global: {
		/**
		 * Feature Me
		 */
		title: () => LocalizedString
	}
}

export type Formatters = {}
